fixing app url output

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -63,7 +63,13 @@ jobs:
       - name: Get Application URL
         id: get-output
         run: |
-          echo "APPLICATION_URL=$(terraform output -raw application_url)" >> $GITHUB_ENV
+          APP_URL=$(terraform output -raw application_url)
+          if [ -z "$APP_URL" ]; then
+            echo "APPLICATION_URL not found or empty. Exiting."
+            exit 1
+          else
+            echo "APPLICATION_URL=$APP_URL" >> $GITHUB_ENV
+          fi
 
       - name: Check Deployment
         run: |
